import type { Manifest, ManifestResource } from "@envmanifest/schema";
import { effectiveName } from "../manifest/reconcile.js";

export interface GenerateTypesOptions {
  env: string;
  manifest: Manifest;
}

export function generateTypesModule(opts: GenerateTypesOptions): string {
  const { manifest, env } = opts;
  const inEnv = (manifest.resources ?? []).filter(
    (r) => r.environments?.includes(env) && r.kind !== "binding",
  );

  const required = inEnv.filter((r) => r.required !== false);
  const optional = inEnv.filter((r) => r.required === false);

  const lines: string[] = [];
  lines.push(`/* eslint-disable */`);
  lines.push(`// Generated by 'envmanifest generate types' for env=${env}.`);
  lines.push(`// Edit the manifest, not this file. Re-run to regenerate.`);
  lines.push(`// Project: ${manifest.project}`);
  lines.push("");
  lines.push(`export interface Env {`);
  for (const r of required) {
    lines.push(`  ${tsKey(effectiveName(r, manifest))}: ${tsType(r)};`);
  }
  for (const r of optional) {
    lines.push(`  ${tsKey(effectiveName(r, manifest))}?: ${tsType(r)};`);
  }
  lines.push(`}`);
  lines.push("");

  const requiredEffectiveNames = required.map((r) => effectiveName(r, manifest));
  lines.push(`const REQUIRED = ${JSON.stringify(requiredEffectiveNames)} as const;`);
  lines.push("");

  lines.push(`function readSource(): Record<string, string | undefined> {`);
  lines.push(`  if (typeof process !== "undefined" && process.env) {`);
  lines.push(`    return process.env as Record<string, string | undefined>;`);
  lines.push(`  }`);
  lines.push(`  return {};`);
  lines.push(`}`);
  lines.push("");

  lines.push(`export function loadEnv(`);
  lines.push(`  source: Record<string, string | undefined> = readSource(),`);
  lines.push(`): Env {`);
  lines.push(`  const missing: string[] = [];`);
  lines.push(`  for (const name of REQUIRED) {`);
  lines.push(`    if (source[name] === undefined || source[name] === "") {`);
  lines.push(`      missing.push(name);`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`  if (missing.length > 0) {`);
  lines.push(`    throw new Error(`);
  lines.push(
    `      "envmanifest: missing required env vars: " + missing.join(", "),`,
  );
  lines.push(`    );`);
  lines.push(`  }`);
  lines.push(`  return source as Env;`);
  lines.push(`}`);
  lines.push("");

  lines.push(`export const env: Env = /* @__PURE__ */ loadEnv();`);
  lines.push("");

  return lines.join("\n");
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function tsType(r: ManifestResource): string {
  if (r.type === "bool") return "string"; // env is always string-typed at runtime
  if (
    r.type === "enum" &&
    Array.isArray(r.values) &&
    r.values.every((v) => typeof v === "string" || typeof v === "number")
  ) {
    return r.values.map((v) => JSON.stringify(String(v))).join(" | ");
  }
  return "string";
}
