import type { Manifest, ManifestResource } from "@envmanifest/schema";

export interface RenderExampleOptions {
  env: string;
  manifest: Manifest;
}

export function renderEnvExample(opts: RenderExampleOptions): string {
  const { env, manifest } = opts;
  const lines: string[] = [];
  lines.push(`# Generated by 'envmanifest example' for env=${env}`);
  lines.push(`# Source: ${manifest.project} (manifest schema v${manifest.version})`);
  lines.push(`# Edit the manifest, not this file. Re-run to regenerate.`);
  lines.push("");

  const grouped = groupByService(manifest.resources ?? [], env);

  for (const [service, resources] of grouped) {
    if (service !== "__all__") {
      lines.push(`# ── service: ${service} ──`);
    }
    for (const r of resources) {
      if (r.platform_generated) continue;
      if (r.deprecated) continue;
      if (r.never_in?.includes(env)) continue;

      if (r.description) {
        for (const line of r.description.split("\n")) {
          lines.push(`# ${line}`);
        }
      }
      const meta: string[] = [r.kind];
      if (r.exposure) meta.push(r.exposure);
      if (r.required === false) meta.push("optional");
      if (r.type) meta.push(`type:${r.type}`);
      lines.push(`# [${meta.join(", ")}]`);

      const placeholder = placeholderFor(r);
      const prefix = r.required === false ? "# " : "";
      lines.push(`${prefix}${r.name}=${placeholder}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function groupByService(
  resources: ManifestResource[],
  env: string,
): Map<string, ManifestResource[]> {
  const out = new Map<string, ManifestResource[]>();
  for (const r of resources) {
    if (!r.environments?.includes(env)) continue;
    const key = r.service ?? "__all__";
    const list = out.get(key);
    if (list) list.push(r);
    else out.set(key, [r]);
  }
  return out;
}

function placeholderFor(r: ManifestResource): string {
  if (r.default !== undefined) return String(r.default);
  if (r.kind === "binding") return "<bound by platform>";
  if (r.type === "bool") return "false";
  if (r.type === "url") return "https://example.com";
  if (r.type === "enum" && Array.isArray(r.values) && r.values.length > 0) {
    return String(r.values[0]);
  }
  if (r.kind === "secret") return "your-secret-here";
  return "";
}
